# Generated by Django 5.2 on 2025-04-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('instructor_name', models.CharField(max_length=50)),
                ('quality', models.IntegerField(default=0)),
                ('material_structure_clarity', models.IntegerField(default=1)),
                ('workload_manageability', models.IntegerField(default=1)),
                ('instructor_quality', models.IntegerField(default=1)),
                ('instructor_clarity', models.IntegerField(default=1)),
                ('instructor_responsive', models.IntegerField(default=1)),
                ('instructor_engangement', models.IntegerField(default=1)),
                ('resources_availabilty', models.IntegerField(default=1)),
                ('assinment_impact', models.IntegerField(default=1)),
                ('course_recommendation', models.BooleanField(default=False)),
                ('suggestion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
