# Generated by Django 5.2 on 2025-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefeedback',
            old_name='instructor_engangement',
            new_name='instructor_engagement',
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='course_recommendation',
            field=models.CharField(max_length=10),
        ),
    ]
